DROP DATABASE IF EXISTS `ZENHOMES`;
CREATE DATABASE `ZENHOMES`;
USE `ZENHOMES`;

CREATE TABLE `ZENHOMES`.`PERSON` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(45) NOT NULL,
PRIMARY KEY (`ID`),
UNIQUE INDEX `PERSON_ID_UNIQUE` (`ID` ASC) VISIBLE);

INSERT INTO `ZENHOMES`.`PERSON` (`ID`, `NAME`) VALUES (1, 'ZENHOMES');
INSERT INTO `ZENHOMES`.`PERSON` (`ID`, `NAME`) VALUES (2, 'EVERTON');
INSERT INTO `ZENHOMES`.`PERSON` (`ID`, `NAME`) VALUES (3, 'LUCCAS');

CREATE TABLE `ZENHOMES`.`LANDLORD` (
	`ID` INT NOT NULL,
INDEX `ID_idx` (`ID` ASC) VISIBLE,
CONSTRAINT `PERSON_ID_LANDLORD`
FOREIGN KEY (`ID`)
REFERENCES `ZENHOMES`.`PERSON` (`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION);
    
INSERT INTO `ZENHOMES`.`LANDLORD` (`ID`) VALUES (1);

CREATE TABLE `ZENHOMES`.`TENANT` (
	`ID` INT NOT NULL,
INDEX `TENANT_ID_IDX` (`ID` ASC) VISIBLE,
CONSTRAINT `PERSON_ID_TENANT`
FOREIGN KEY (`ID`)
REFERENCES `ZENHOMES`.`PERSON` (`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION);

INSERT INTO `ZENHOMES`.`TENANT` (`ID`) VALUES (2);
INSERT INTO `ZENHOMES`.`TENANT` (`ID`) VALUES (3);

CREATE TABLE `ZENHOMES`.`ADDRESS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`STREET` VARCHAR(45) NOT NULL,
PRIMARY KEY (`ID`),
UNIQUE INDEX `ADDRESS_ID_UNIQUE` (`ID` ASC) VISIBLE);

INSERT INTO `ZENHOMES`.`ADDRESS` (`ID`, `STREET`) VALUES (1, 'STREET');

CREATE TABLE `ZENHOMES`.`BUILDING` (
	`ID` INT NOT NULL,
	`NAME` VARCHAR(45) NOT NULL,
	`ADDRESS_FK` INT NOT NULL,
PRIMARY KEY (`ID`),
CONSTRAINT `BUILDING_ADDRESS_FK`
FOREIGN KEY (`ADDRESS_FK`)
REFERENCES `ZENHOMES`.`ADDRESS` (`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION);

INSERT INTO `ZENHOMES`.`BUILDING` (`ID`, `NAME`, `ADDRESS_FK`) VALUES (1, 'BUILDING', 1);

CREATE TABLE `ZENHOMES`.`APARTMENT` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NUMBER` INT NULL,
	`PRICE` DECIMAL(10,2) NULL,
	`BUILDING_FK` INT NOT NULL,
	`LANDLORD_FK` INT NOT NULL,
PRIMARY KEY (`ID`),
CONSTRAINT `APARTMENT_BUILDING_FK`
FOREIGN KEY (`BUILDING_FK`)
REFERENCES `ZENHOMES`.`BUILDING` (`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
CONSTRAINT `BUILDING_LANDLORD_FK`
FOREIGN KEY (`LANDLORD_FK`)
REFERENCES `ZENHOMES`.`LANDLORD` (`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION);

INSERT INTO `ZENHOMES`.`APARTMENT` (`ID`, `NUMBER`, `PRICE`, `BUILDING_FK`, `LANDLORD_FK`) VALUES (1, 1, 1000, 1, 1);
INSERT INTO `ZENHOMES`.`APARTMENT` (`ID`, `NUMBER`, `PRICE`, `BUILDING_FK`, `LANDLORD_FK`) VALUES (2, 2, 2000, 1, 1);
    
CREATE TABLE `ZENHOMES`.`FEATURE` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(45) NOT NULL,
PRIMARY KEY (`ID`),
UNIQUE INDEX `FEATURE_ID_UNIQUE` (`ID` ASC) VISIBLE);

INSERT INTO `ZENHOMES`.`FEATURE` (`ID`, `NAME`) VALUES (1, 'NAME');

CREATE TABLE `ZENHOMES`.`FEATURE_APARTMENT` (
  `FEATURE_FK` INT NOT NULL,
  `APARTMENT_FK` INT NOT NULL,
  PRIMARY KEY (`FEATURE_FK`, `APARTMENT_FK`),
  CONSTRAINT `FEATURE_APARTMENT_FEATURE_FK`
    FOREIGN KEY (`FEATURE_FK`)
    REFERENCES `ZENHOMES`.`FEATURE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FEATURE_APARTMENT_APARTMENT_FK`
    FOREIGN KEY (`APARTMENT_FK`)
    REFERENCES `ZENHOMES`.`APARTMENT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

INSERT INTO `ZENHOMES`.`FEATURE_APARTMENT` (`FEATURE_FK`, `APARTMENT_FK`) VALUES (1, 1);

CREATE TABLE `ZENHOMES`.`CONTRACT` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NUMBER` INT NOT NULL,
	`DATE` DATETIME NOT NULL,
	`TERM` DATETIME NOT NULL,
	`LANDLORD_FK` INT NOT NULL,
	`APARTMENT_FK` INT NOT NULL,
PRIMARY KEY (`ID`),
UNIQUE INDEX `CONTRACT_ID_UNIQUE` (`ID` ASC) VISIBLE,    
UNIQUE INDEX `NUMBER_UNIQUE` (`NUMBER` ASC) VISIBLE,
INDEX `LANDLORD_FK_IDX` (`LANDLORD_FK` ASC) VISIBLE,
INDEX `APARTMENT_FK_IDX` (`APARTMENT_FK` ASC) VISIBLE,
CONSTRAINT `CONTRACT_LANDLORD_FK`
FOREIGN KEY (`LANDLORD_FK`)
REFERENCES `ZENHOMES`.`LANDLORD` (`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION,
CONSTRAINT `CONTRACT_APARTMENT_FK`
FOREIGN KEY (`APARTMENT_FK`)
REFERENCES `ZENHOMES`.`APARTMENT` (`ID`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION);

INSERT INTO `ZENHOMES`.`CONTRACT` (`ID`, `NUMBER`, `DATE`, `TERM`, `LANDLORD_FK`, `APARTMENT_FK`) VALUES (1, 1, CURDATE(), CURDATE(), 1, 1);

CREATE TABLE `ZENHOMES`.`CONTRACT_TENANT` (
  `CONTRACT_FK` INT NOT NULL,
  `TENANT_FK` INT NOT NULL,
  PRIMARY KEY (`CONTRACT_FK`, `TENANT_FK`),
  INDEX `ID_idx` (`TENANT_FK` ASC) VISIBLE,
  CONSTRAINT `CONTRACT_TENANT_CONTRACT_FK`
    FOREIGN KEY (`CONTRACT_FK`)
    REFERENCES `ZENHOMES`.`CONTRACT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CONTRACT_TENANT_TENANT_FK`
    FOREIGN KEY (`TENANT_FK`)
    REFERENCES `ZENHOMES`.`TENANT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

INSERT INTO `ZENHOMES`.`CONTRACT_TENANT` (`CONTRACT_FK`, `TENANT_FK`) VALUES (1, 2);
INSERT INTO `ZENHOMES`.`CONTRACT_TENANT` (`CONTRACT_FK`, `TENANT_FK`) VALUES (1, 3);

SELECT * FROM `ZENHOMES`.`CONTRACT` CONTRACT
	LEFT JOIN `ZENHOMES`.`LANDLORD` LANDLORD
		ON CONTRACT.LANDLORD_FK = LANDLORD.ID
	LEFT JOIN `ZENHOMES`.`PERSON` PERSON_LANDLORD
		ON LANDLORD.ID = PERSON_LANDLORD.ID
	LEFT JOIN `ZENHOMES`.`APARTMENT` APARTMENT
		ON CONTRACT.APARTMENT_FK = APARTMENT.ID
	LEFT JOIN `ZENHOMES`.`BUILDING` BUILDING
		ON APARTMENT.BUILDING_FK = BUILDING.ID
	LEFT JOIN `ZENHOMES`.`ADDRESS` ADDRESS
		ON BUILDING.ADDRESS_FK = ADDRESS.ID
	LEFT JOIN `ZENHOMES`.`CONTRACT_TENANT` CONTRACT_TENANT
		ON CONTRACT_TENANT.CONTRACT_FK = CONTRACT.ID
	LEFT JOIN `ZENHOMES`.`TENANT` TENANT
		ON CONTRACT_TENANT.TENANT_FK = TENANT.ID
	LEFT JOIN `ZENHOMES`.`PERSON` PERSON_TENANT
		ON TENANT.ID = PERSON_TENANT.ID;

