
  DROP DATABASE `ZENHOMES`;
  CREATE DATABASE `ZENHOMES`;
  USE `ZENHOMES`;

  CREATE TABLE `ZENHOMES`.`PERSON` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE);

    CREATE TABLE `ZENHOMES`.`LANDLORD` (
      `ID` INT NOT NULL,
      INDEX `ID_idx` (`ID` ASC) VISIBLE,
      CONSTRAINT `ID_LANDLORD`
        FOREIGN KEY (`ID`)
        REFERENCES `ZENHOMES`.`PERSON` (`ID`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION);

    CREATE TABLE `ZENHOMES`.`TENANT` (
      `ID` INT NOT NULL,
      INDEX `ID_idx` (`ID` ASC) VISIBLE,
      CONSTRAINT `ID_TENANT`
        FOREIGN KEY (`ID`)
        REFERENCES `ZENHOMES`.`PERSON` (`ID`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION);

    CREATE TABLE `ZENHOMES`.`APARTMENT` (
      `ID` INT NOT NULL AUTO_INCREMENT,
      `NUMBER` INT NULL,
      `PRICE` DECIMAL(10,2) NULL,
      PRIMARY KEY (`ID`),
      UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE);

    CREATE TABLE `ZENHOMES`.`BUILDING` (
      `ID` INT NOT NULL,
      `NAME` VARCHAR(45) NOT NULL,
      PRIMARY KEY (`ID`));

      CREATE TABLE `ZENHOMES`.`CONTRACT` (
        `NUMBER` INT NOT NULL AUTO_INCREMENT,
        `DATE` DATETIME NOT NULL,
        `TERM` DATETIME NOT NULL,
        `LANDLORD_FK` INT NOT NULL,
        `APARTMENT_FK` INT NOT NULL,
        PRIMARY KEY (`NUMBER`),
        UNIQUE INDEX `NUMBER_UNIQUE` (`NUMBER` ASC) VISIBLE,
        INDEX `ID_idx` (`LANDLORD_FK` ASC) VISIBLE,
        INDEX `ID_idx1` (`APARTMENT_FK` ASC) VISIBLE,
        CONSTRAINT `LANDLORD_FK`
          FOREIGN KEY (`LANDLORD_FK`)
          REFERENCES `ZENHOMES`.`LANDLORD` (`ID`)
          ON DELETE NO ACTION
          ON UPDATE NO ACTION,
        CONSTRAINT `APARTMENT_FK`
          FOREIGN KEY (`APARTMENT_FK`)
          REFERENCES `ZENHOMES`.`APARTMENT` (`ID`)
          ON DELETE NO ACTION
          ON UPDATE NO ACTION);
          
CREATE TABLE `ZENHOMES`.`FEATURE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE);
  
CREATE TABLE `ZENHOMES`.`ADDRESS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `STREET` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE);

